### ISSUE TITLE
TeX以外のフォーマットについて

### ISSUE THREAD

**Issue by yasu80** [CIR-KIT/TsukubaChallengeReports#3]
自分はTeXに不慣れであるので, TeX以外で書きたいのですが, みっともないでしょうか.

**Comment by AriYu** [comment]
@yasu80 
なんでもいいですよ。
2015年のやつを参考にして適当に2段組で書いてください。

**Comment by yasu80** [comment]
今日中になんとかします.

**Comment by yamacir-kit** [comment]
@yasu80 は書き上げたみたいですが，レポートして見た場合かなりアレだと思います
`yasu/add_draft`ブランチの`TsukubaChallengeReports/2016/fifth_robot/tsukuba/`以下に初めの部分を書き直したものが上がっていますが，全体を見直すには明日の17時には間に合いそうにありません

彼が仕上げたもので構わないなら勿論なんの問題もありませんが，期限の延長をしていただけるならいくらかマシなものが出来ると思います

**Comment by AriYu** [comment]
@YamaCIR-KIT 
指導ありがとう。
できるだけ良いほうが望ましいとは思いますが、現状でもダメというほどでは無いので、時間内でできるだけ良い物に仕上げられたらと思います。
別に5号機レポート用のissueを作るので続きはそちらでお願いします。

**Comment by yamacir-kit** [comment]
わかりました
出すぎた真似をしました

では僕は見守り隊にジョブチェンジします

**Comment by AriYu** [comment]
@YamaCIR-KIT 
いやいや、出来たら手伝ってあげて下さい。
よろしくお願いします。
