### ISSUE TITLE
5号機レポートについて

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/TsukubaChallengeReports#8]
@yasu80 
レポートお疲れ様です。
いくつか、気になった点を記します。

タイトル
 筆者は開発に関わった１，２年生全員を載せていいです。
3章
  - 釣行 -> 兆候のミス？

他はまだ見直しているところだと思うので、ある程度出来たらまたコメント残してください。

**Comment by AriYu** [comment]
利用したURGの型番や改造のために必要な部品やどこで買ったとかもできるだけ記述をお願いします。

**Comment by yasu80** [comment]
ご指摘ありがとうございます.
加えて, 図の番号を振り直していきます

**Comment by AriYu** [comment]
@yasu80 
TeXで書くなら`label`を貼ってそれを参照するようにしてください。

**Comment by yasu80** [comment]
@AriYu 
TeXの環境整備をしていない(使ったことがない)ため, 今回は Writer で仕上げています.
